[package]
name = "aoc2015"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
thiserror = "2.0.12"
ureq = { version = "3.0.12" }
regex = "1.11.1"
itertools = "0.14.0"
serde = { version = "1.0" }
serde_json = "1.0"